Update create_version_bump_PR.yml

diff --git a/.github/workflows/create_version_bump_PR.yml b/.github/workflows/create_version_bump_PR.yml
--- a/.github/workflows/create_version_bump_PR.yml
+++ b/.github/workflows/create_version_bump_PR.yml
@@ -17,10 +17,23 @@ jobs:
     runs-on: ubuntu-latest
     env:
       GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-      Version: "${{ github.event.inputs.version }}"
-      IsPrerelease: "${{ github.event.inputs.is_prerelease }}"
 
     steps:
+      - name: Set Variables
+      - run: |
+          if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
+            echo "::set-output name=version::${{ github.event.inputs.version }}"
+            echo "::set-output name=tracer_version::${{ github.event.inputs.tracer_version }}"
+          elif [[ -z "${{ github.event.client_payload.version }}" ]]; then
+            TRACERVERSION=${Version_FromDispatch:1}
+            echo $TRACERVERSION
+            echo "::set-output name=version::$TRACERVERSION00"
+            echo "::set-output name=tracer_version::$TRACERVERSION"
+          elif
+            echo "Error. Input versions aren't set"
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v2
 
@@ -44,7 +57,7 @@ jobs:
           CURRENT_DEV_VERSION="$(grep -o -e DEVELOPMENT_VERSION\=\"$versionRegex dotnet/build-packages.sh | sed 's/DEVELOPMENT_VERSION="//')"
           echo Current dev version is: $CURRENT_DEV_VERSION
           
-          VERSION=${{ github.event.inputs.version }}
+          VERSION=${{ steps.versions.outputs.version }}
           echo Bumping extension version to $VERSION
           
           sed -i -e "s/RELEASE_VERSION=\"$CURRENTVERSION\"/RELEASE_VERSION=\"$VERSION\"/g" dotnet/build-packages.sh
@@ -68,7 +81,7 @@ jobs:
           
           PR_BODY="Bumps the release version to $VERSION."
           
-          TRACER_VERSION=${{ github.event.inputs.tracer_version }}
+          TRACER_VERSION=${{steps.versions.outputs.tracer_version}}
           if [ -n "$TRACER_VERSION" ]; then
             CURRENT_TRACER_VERSION="$(grep -o -e dd-trace-dotnet/releases/download/v$versionRegex dotnet/build-packages.sh | sed 's#dd-trace-dotnet/releases/download/v##')"
             echo Current tracer version is: $CURRENT_TRACER_VERSION
