Update create_version_bump_PR.yml

diff --git a/.github/workflows/create_version_bump_PR.yml b/.github/workflows/create_version_bump_PR.yml
--- a/.github/workflows/create_version_bump_PR.yml
+++ b/.github/workflows/create_version_bump_PR.yml
@@ -20,6 +20,21 @@ jobs:
 
     steps:
 
+      - name: "Set Variables"
+      - run: |
+          if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
+            echo "::set-output name=version::${{ github.event.inputs.version }}"
+            echo "::set-output name=tracer_version::${{ github.event.inputs.tracer_version }}"
+          elif [[ ! -z "${{ github.event.client_payload.version }}" ]]; then
+            TRACERVERSION=${Version_FromDispatch:1}
+            echo $TRACERVERSION
+            echo "::set-output name=version::$TRACERVERSION00"
+            echo "::set-output name=tracer_version::$TRACERVERSION"
+          elif
+            echo "Error. Input versions are not set"
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v2
 
